clear all; close all; clc;
tic;% Start the timer
M1 = 1; M2 = 2; % Mean of X and Y resp.
V1 = 4; V2 = 9; % Variance of X and Y resp.
i = 1; % the random number generated by the algorithm 
% Generate X & Y that are N(0,1) independent RVs
while(i<=1000000)
    u1 = 2*rand()-1; u2 = 2*rand()-1;
    s = u1^2 + u2^2;
    if(s < 1)
        i = i + 1;
        X(i) = sqrt(-2*log(s)/s)*u1;
        Y(i) = sqrt(-2*log(s)/s)*u2;
    end
end
% Scale them to a particular mean and variance 
x = sqrt(V1)*X + M1; % x~ N(M1,V1)
y = sqrt(V2)*Y + M2; % y~ N(M2,V2)
toc; % Read elapsed time from stopwatch
Mean_Variance_x = [mean(x) var(x)]
Mean_Variance_y = [mean(y) var(y)]
Covariance_x_y = cov(x,y)